version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest 
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - iaas-firecracker-network

volumes:
  rabbitmq_data:

networks:
  iaas-firecracker-network:
    external: true
    name: service-config_iaas-firecracker-network  # Replace with actual network name