services:

  service-registry:
    restart: 'on-failure'
    build: .
    ports:
      - "8761:8761" # Port pour le service d'enregistrement
    environment:
      - SPRING_APPLICATION_NAME=service-registry
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8080
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8080
    networks:
      - iaas-firecracker-network

networks:
  iaas-firecracker-network:
    external: true
    name: service-config_iaas-firecracker-network  # Replace with actual network name
    