services:
  service-cluster:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - iaas-firecracker-network
  

  ### Service Cluster Database ###

  mysql_db_service_cluster:
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: service_cluster_db
      MYSQL_ROOT_PASSWORD: firecracker
      MYSQL_PASSWORD: firecracker
      MYSQL_USER: firecracker
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "fireCracker", "-pfirecracker"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - iaas-firecracker-network

  
  ### Service PHPMyAdmin ###

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql_db_service_cluster
      PMA_USER: firecracker
      PMA_PASSWORD: firecracker
    ports:
      - "7003:80"
    depends_on:
      - mysql_db_service_cluster
    networks:
      - iaas-firecracker-network

networks:
  iaas-firecracker-network:
    external: true
    name: service-config_iaas-firecracker-network

volumes:
  mysql_data:
    driver: local
